# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"independent_samples": "00_stats.ipynb"}

modules = ["stats.py"]

doc_url = "https://DSegebarth.github.io/dcl_stats_n_plots/"

git_url = "https://github.com/DSegebarth/dcl_stats_n_plots/tree/master/"

def custom_doc_links(name): return None
