# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"independent_samples": "00_stats.ipynb",
         "one_sample": "00_stats.ipynb",
         "mixed_model_ANOVA": "00_stats.ipynb",
         "DEFAULT_PARAMS": "01_plots.ipynb",
         "l_required_keys_ind_samples": "01_plots.ipynb",
         "l_required_keys_one_sample": "01_plots.ipynb",
         "l_required_keys_mma": "01_plots.ipynb",
         "plot_independent_samples": "01_plots.ipynb",
         "initialize_plot": "01_plots.ipynb",
         "finish_show_and_save_plot": "01_plots.ipynb",
         "annotate_stats_independent_samples": "01_plots.ipynb",
         "get_stars_str": "01_plots.ipynb",
         "plot_one_sample": "01_plots.ipynb",
         "annotate_stats_one_sample": "01_plots.ipynb",
         "plot_mma": "01_plots.ipynb",
         "annotate_stats_mma": "01_plots.ipynb",
         "annotate_stats_mma_pointplot": "01_plots.ipynb",
         "sort_by_third": "01_plots.ipynb",
         "STYLE": "02_gui.ipynb",
         "INITIAL_WIDGET_PARAMS": "02_gui.ipynb",
         "Gui": "02_gui.ipynb",
         "Select_stats_widget": "02_gui.ipynb",
         "Select_plots_widget": "02_gui.ipynb",
         "Select_downloads_widget": "02_gui.ipynb",
         "Customization_widget": "02_gui.ipynb",
         "Customize_annotations": "02_gui.ipynb",
         "Select_annotations": "02_gui.ipynb",
         "Customize_y_axis": "02_gui.ipynb",
         "Customize_x_axis": "02_gui.ipynb",
         "Customize_both_axes": "02_gui.ipynb",
         "Customize_other_features": "02_gui.ipynb"}

modules = ["stats.py",
           "plots.py",
           "gui.py"]

doc_url = "https://DSegebarth.github.io/dcl_stats_n_plots/"

git_url = "https://github.com/DSegebarth/dcl_stats_n_plots/tree/master/"

def custom_doc_links(name): return None
